
QUES 3

DROP TABLE PERFORMANCE_REVIEW;
CREATE TABLE PERFORMANCE_REVIEW(
    REVIEW_ID VARCHAR2(10),
    EMPLOYEE_ID NUMBER,
    REVIEW_YEAR NUMBER,
    RATING NUMBER(1), 
    REMARKS VARCHAR2(100),

    CONSTRAINT PK_EMP PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_EMP 
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES(EMPLOYEE_ID),

    CONSTRAINT CK_RATING
    CHECK(RATING BETWEEN 1 AND 5)
);


INSERT INTO PERFORMANCE_REVIEW
VALUES ('R001', 100, 2026, 5, 'Excellent performance');

SELECT * 
FROM PERFORMANCE_REVIEW;


QUES 4
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
SUBSTR(FIRST_NAME,1,3) || SUBSTR(PHONE_NUMBER,  -3) AS USERID
FROM EMPLOYEES
WHERE LENGTH(PHONE_NUMBER)>=10
AND (DEPARTMENT_ID=50 OR DEPARTMENT_ID=80)
--AND DEPARTMENT IN (50, 80)
ORDER BY LENGTH(FIRST_NAME) DESC;

QUES 5
  
SELECT JOB_ID, 
MAX(SALARY)-MIN(SALARY) AS SALARY_GAP
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING (MAX(SALARY)-MIN(SALARY))>3000
AND AVG(SALARY)>=6000
ORDER BY (MAX(SALARY)-MIN(SALARY)) DESC;
