QUES 1
  
SELECT 
SUBSTR(PHONE_NUMBER,1, INSTR(PHONE_NUMBER, '.')-1) AS COUNTRY_CODE,
COUNT(*) AS NUMBER_OF_EMPLOYEES
FROM EMPLOYEES 
WHERE HIRE_DATE> DATE '2005-01-01'
GROUP BY SUBSTR(PHONE_NUMBER, 1, INSTR(PHONE_NUMBER, '.')-1);


QUES 2

SELECT EMPLOYEE_ID, SALARY, SALARY, ABS(SALARY-ROUND(SALARY/1000)*1000) AS SALARY_DIFF
FROM EMPLOYEES;

QUES 3

CREATE TABLE EMP_TRAINING(
    TRAINING_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER,
    TRAINING_NAME VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT EMP_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

INSERT INTO EMP_TRAINING
VALUES(1234,101,'DBMS',DEFAULT);

SELECT * 
FROM EMP_TRAINING;

QUES 4

SELECT DEPARTMENT_ID,
TO_CHAR(SUM(SALARY*12), '99,999,999') AS TOTAL_PAYOUT
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>=1
AND MIN(SALARY)>=2500;

QUES 5
SELECT EMPLOYEE_ID, 
(UPPER(SUBSTR(FIRST_NAME,1,2))||LENGTH(LAST_NAME)||SUBSTR(PHONE_NUMBER,-1)) AS SECURITY_CODE
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME)>LENGTH(LAST_NAME)
ORDER BY LENGTH(SECURITY_CODE) DESC;
