QUES 4

SELECT EMPLOYEE_ID,
HIRE_DATE,
NVL(TO_CHAR(COMMISSION_PCT), 'NO COMMISSION') AS COMMISSION_PERCENTAGE
FROM EMPLOYEES
WHERE SALARY>8000
AND EXTRACT(MONTH FROM HIRE_DATE)IN (12,1,2)
ORDER BY CASE EXTRACT(MONTH FROM HIRE_DATE)
WHEN 12 THEN 1
WHEN 1 THEN 2
WHEN 2 THEN 3
END;


QUES 5
SELECT MANAGER_ID, SUM(SALARY) AS TOTAL_MONTHLY_LIABILITY
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING SUM(SALARY)>30000
AND COUNT(*)>=5
ORDER BY SUM(SALARY) DESC;
