SALAMI QUES 1
SELECT 
CASE 
    WHEN TO_NUMBER(TO_CHAR(HIRE_DATE, 'MM')) BETWEEN 1 AND 4 THEN 'FIRST_QUARTER'
    WHEN TO_NUMBER(TO_CHAR(HIRE_DATE, 'MM')) BETWEEN 5 AND 8 THEN 'SECOND_QUARTER'
    WHEN TO_NUMBER(TO_CHAR(HIRE_DATE, 'MM')) BETWEEN 9 AND 12 THEN 'THIRD_QUARTER'
    END AS QUARTER, COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY CASE 
    WHEN TO_NUMBER(TO_CHAR(HIRE_DATE, 'MM')) BETWEEN 1 AND 4 THEN 'FIRST_QUARTER'
    WHEN TO_NUMBER(TO_CHAR(HIRE_DATE, 'MM')) BETWEEN 5 AND 8 THEN 'SECOND_QUARTER'
    WHEN TO_NUMBER(TO_CHAR(HIRE_DATE, 'MM')) BETWEEN 9 AND 12 THEN 'THIRD_QUARTER'
    END
ORDER BY QUARTER;


QUES 2


SELECT LPAD(FIRST_NAME||' '||LAST_NAME,20,' ') AS FULL_NAME
FROM EMPLOYEES
ORDER BY LENGTH(FIRST_NAME || ' ' || LAST_NAME)ASC;


QUES 3

SELECT COUNTRY_ID,
case
WHEN STREET_ADDRESS IS NOT NULL
AND CITY IS NOT NULL 
AND STATE_PROVINCE IS NOT NULL 
AND POSTAL_CODE IS NOT NULL 
THEN '(' || STREET_ADDRESS||','||CITY||','||STATE_PROVINCE||'-'||POSTAL_CODE||')'
ELSE null
END AS ADDRESS 
FROM LOCATIONS
ORDER BY 
COUNTRY_ID ASC,
POSTAL_CODE DESC;

QUES 4

SELECT DEPARTMENT_ID, JOB_ID,
MIN(HIRE_DATE) AS FIRST_HIRE,
MAX(HIRE_DATE) AS LAST_HIRE,
ROUND(AVG(SALARY),2) AS  AVG_SAL
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT null
AND JOB_ID IS NOT null
AND HIRE_DATE IS NOT null
AND SALARY IS NOT NULL
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING AVG(SALARY)>8000
ORDER BY DEPARTMENT_ID;

