

SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING SUM(
    CASE 
        WHEN SYSDATE-HIRE_DATE<=600
        THEN 1
        ELSE 0
        END
)<=1
ORDER BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID, MIN(HIRE_DATE), MAX(HIRE_DATE), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY (MAX(HIRE_DATE)-MIN(HIRE_DATE)) ASC,
    AVG(SALARY) DESC;


SELECT FIRST_NAME || ' ' || LAST_NAME AS FULLNAME, 
(SALARY*12) AS ANNSAL, 
SALARY AS MONSAL, 
NVL(COMMISSION_PCT*100, 0) AS CMSN_PCT,
CASE 
    WHEN COMMISSION_PCT IS NOT NULL 
    THEN(SALARY*12+SALARY*12*COMMISSION_PCT)/12
    ELSE (SALARY*12-SALARY*12*0.05)/12
    END AS INCREAMENT_SAL
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID;


SELECT MANAGER_ID, AVG(SALARY) AS SAL,
COUNT(*) AS EMP_CNT 
FROM EMPLOYEES
WHERE EXTRACT(MONTH FROM HIRE_DATE) IN (3,9,12) 
GROUP BY MANAGER_ID
HAVING AVG(salary) = TRUNC(AVG(salary))
ORDER BY EMP_CNT ASC,
        AVG(SALARY) DESC;
