--a
SELECT E.LAST_NAME, E.SALARY, J.JOB_TITLE
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID;

--b
SELECT D.DEPARTMENT_NAME, C.COUNTRY_NAME
FROM DEPARTMENTS D 
join LOCATIONS L 
ON D.LOCATION_ID=L.LOCATION_ID
JOIN COUNTRIES C 
ON L.COUNTRY_ID=C.COUNTRY_ID;

--c
SELECT  C.COUNTRY_NAME, COUNT(D.DEPARTMENT_ID)
FROM DEPARTMENTS D 
JOIN LOCATIONS L 
ON L.LOCATION_ID=D.LOCATION_ID 
JOIN COUNTRIES C 
ON L.COUNTRY_ID=C.COUNTRY_ID
GROUP BY C.COUNTRY_NAME;

--d
SELECT E.EMPLOYEE_ID, COUNT(J.START_DATE)
FROM EMPLOYEES E 
LEFT JOIN JOB_HISTORY J 
ON E.JOB_ID=J.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID;

--e
SELECT J.JOB_TITLE, COUNT(E.EMPLOYEE_ID), D.DEPARTMENT_NAME
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID 
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY J.JOB_TITLE, D.DEPARTMENT_NAME;

--f
SELECT E.LAST_NAME, COUNT(O.EMPLOYEE_ID)
FROM EMPLOYEES E 
JOIN EMPLOYEES O 
ON E.HIRE_DATE>O.HIRE_DATE
GROUP BY E.LAST_NAME;

--g
SELECT E.LAST_NAME , COUNT(E1.EMPLOYEE_ID) AS BEFORE, 
COUNT(E2.EMPLOYEE_ID)AS AFTER
FROM EMPLOYEES E 
JOIN EMPLOYEES E1 
ON E.HIRE_DATE>E1.HIRE_DATE
JOIN EMPLOYEES E2 
ON E.HIRE_DATE<E2.HIRE_DATE
GROUP BY E.LAST_NAME;

--h
SELECT E.EMPLOYEE_ID
FROM EMPLOYEES E 
WHERE (
    SELECT COUNT(O.EMPLOYEE_ID)
    FROM EMPLOYEES O 
    WHERE E.SALARY>O.SALARY
) >=3;


--THE PROBLEMS BELLOW ARE QUITE TRICKY
--i
SELECT LAST_NAME,
RANK() OVER (ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

--WITHOUT RANK FUNCTION
SELECT E.LAST_NAME,
1+(
    SELECT COUNT(*)
    FROM EMPLOYEES E2
    WHERE E2.SALARY>E.SALARY
)AS SALARY_RANK
FROM EMPLOYEES E
ORDER BY E.SALARY DESC;


--j
SELECT LAST_NAME, SALARY
FROM EMPLOYEES E
WHERE (
    SELECT COUNT(DISTINCT SALARY)
    FROM EMPLOYEES 
    WHERE SALARY>E.SALARY
)<3;
