--CHAPTER 11.3 (11.1 AND 11.2 ER QUESTIONS TO BOI E DEKHI NA)

--a

SELECT DEPARTMENT_ID, (CASE
WHEN SALARY < 5000 THEN 'C'
WHEN SALARY < 10000 THEN 'B'
WHEN SALARY < 15000 THEN 'A'
ELSE 'A+'
END) "SALARY GRADE", COUNT(*)
FROM EMPLOYEES
GROUP BY (CASE
WHEN SALARY < 5000 THEN 'C'
WHEN SALARY < 10000 THEN 'B'
WHEN SALARY < 15000 THEN 'A'
ELSE 'A+'
END), DEPARTMENT_ID;

--THE WAY BOOK WANTS ME TO SOLVE
SELECT DEPARTMENT_ID,
COUNT(CASE WHEN SALARY<5000 THEN 1 END) AS "C",
COUNT(CASE WHEN SALARY>=5000 AND SALARY<15000 THEN 1 END)AS "B",
COUNT(CASE WHEN SALARY>=15000 AND SALARY<20000 THEN 1 END)AS "A"
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID;


--b
SELECT DEPARTMENT_ID,
SUM(DECODE(SIGN(SALARY-5000), -1, 1, 0))AS "C",
SUM(DECODE(SIGN(SALARY-5000), -1, 0, DECODE(SIGN(SALARY-10000),-1,1,0)))AS "B"
--PORER LEVEL GULAO DEOYA LAGBE
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--c
SELECT E.EMPLOYEE_ID, E2.EMPCNT, M2.EMPCNT
FROM (
    SELECT DEPARTMENT_ID, COUNT(*) AS EMPCNT
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
)E2, EMPLOYEES E,(
    SELECT DEPARTMENT_ID, COUNT(*) AS EMPCNT
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
)M2, EMPLOYEES M
WHERE E.DEPARTMENT_ID=E2.DEPARTMENT_ID
AND E.MANAGER_ID=M.EMPLOYEE_ID
AND M.DEPARTMENT_ID=M2.DEPARTMENT_ID;



