--6.2
--a
SELECT E.LAST_NAME, E.SALARY
FROM EMPLOYEES E 
WHERE (
    SELECT COUNT(*)
    FROM EMPLOYEES E2
    WHERE E.SALARY>E2.SALARY
)>=3;

--b
SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D 
WHERE(
    SELECT AVG(E.SALARY)
    FROM EMPLOYEES E
    WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
)>ALL(
    SELECT MIN(E2.SALARY)
    FROM EMPLOYEES E2
    WHERE E.DEPARTMENT_ID<>E2.DEPARTMENT_ID
    GROUP BY E2.DEPARTMENT_ID
);

--c
SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D 
WHERE(
    SELECT COUNT(*)
    FROM EMPLOYEES E 
    WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID 
)>=ALL(
    SELECT COUNT(*)
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
);

--d
SELECT E.LAST_NAME
FROM EMPLOYEES E 
WHERE EXISTS (
    SELECT *
    FROM JOB_HISTORY O 
    WHERE O.EMPLOYEE_ID=E.EMPLOYEE_ID
    AND E.DEPARTMENT_ID<>O.DEPARTMENT_ID
);

--e
SELECT E.LAST_NAME, D.MINSAL, D.MAXSAL
FROM EMPLOYEES E, (
    SELECT DEPARTMENT_ID, MIN(SALARY) AS MINSAL, MAX(SALARY) AS MAXSAL
    FROM EMPLOYEES 
    GROUP BY DEPARTMENT_ID
) D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY E.SALARY;


--f
SELECT J.JOB_TITLE, E.LAST_NAME
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID
WHERE E.SALARY=(
    SELECT MAX(M.SALARY)   
     FROM EMPLOYEES M 
    WHERE E.JOB_ID=M.JOB_ID
);



