--7.1 a
SELECT EMPLOYEE_ID
FROM EMPLOYEES E 
MINUS 
SELECT M.MANAGER_ID
FROM EMPLOYEES M 
WHERE M.MANAGER_ID IS NOT NULL;

--b
SELECT LAST_NAME
FROM EMPLOYEES 
minus
SELECT LAST_NAME
FROM EMPLOYEES 
WHERE EMPLPOYEE_ID IN(
    SELECT MANAGER_ID
    FROM EMPLOYEES 
    WHERE MANAGER_ID IS NOT NULL
);

--c
SELECT LOCATION_ID
FROM LOCATIONS
minus
SELECT LOCATION_ID
FROM DEPARTMENTS
WHERE LOCATION_ID IS NOT NULL;
