--6.1
--a
SELECT LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID=(
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME='Sales'
);

--b
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY> ANY(
    SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID=(
        SELECT DEPARTMENT_ID
        FROM DEPARTMENTS
        WHERE DEPARTMENT_NAME='Sales'
    )
);

--c
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY> ALL(
    SELECT SALARY
    FROM EMPLOYEES
     WHERE DEPARTMENT_ID = (
        SELECT DEPARTMENT_ID
        FROM DEPARTMENTS
        WHERE DEPARTMENT_NAME = 'Sales'
    )
);

--d
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN (
    SELECT AVG(SALARY)+5000
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID(
        SELECT DEPARTMENT_ID
        FROM DEPARTMENTS
        WHERE DEPARTMENT_NAMES='Sales'
    )
) AND (
    SELECT AVG(SALARY)-5000
    FROM EMPLOYEES
     WHERE DEPARTMENT_ID(
        SELECT DEPARTMENT_ID
        FROM DEPARTMENTS
        WHERE DEPARTMENT_NAMES='Sales'
    )
);
