--1
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME
FROM EMPLOYEES E 
JOIN JOBS J 
ON J.JOB_ID=E.JOB_ID 
WHERE (
    SELECT COUNT(*)
    FROM EMPLOYEES E1
    WHERE E.DEPARTMENT_ID=E1.DEPARTMENT_ID 
)>5
OR (
    SELECT J1.MIN_SALARY
    FROM JOBS J1 
    WHERE E.JOB_ID=J1.JOB_ID
)>10000
AND E.DEPARTMENT_ID NOT IN(
SELECT D.DEPARTMENT_ID
FROM DEPARTMENTS D 
JOIN EMPLOYEES M 
ON D.MANAGER_ID=M.EMPLOYEE_ID 
WHERE M.SALARY<(
    SELECT AVG(E2.SALARY)
    FROM EMPLOYEES E2 
    WHERE E2.DEPARTMENT_ID = D.DEPARTMENT_ID
)
);

--2
SELECT C.COUNTRY_NAME, COUNT(*) AS DEPT_CNT 
FROM COUNTRIES C 
LEFT JOIN LOCATIONS L 
ON C.COUNTRY_ID=L.COUNTRY_ID
LEFT JOIN DEPARTMENTS D 
ON L.LOCATION_ID=D.LOCATION_ID 
GROUP BY C.COUNTRY_NAME
ORDER BY C.COUNTRY_NAME ASC;


--3
SELECT E.EMPLOYEE_ID,
e.first_name || ' ' || e.last_name AS full_name
, E.SALARY, D.DEPARTMENT_NAME, J.JOB_TITLE
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
JOIN JOBS J 
ON J.JOB_ID=E.JOB_ID 
WHERE (
    SELECT COUNT(*)
    FROM EMPLOYEES E2
    WHERE E.DEPARTMENT_ID=E2.DEPARTMENT_ID
)>=2
AND E.SALARY=(
    SELECT MAX(E4.SALARY)
    FROM EMPLOYEES E4 
    WHERE E4.DEPARTMENT_ID=E.DEPARTMENT_ID 
    AND E4.SALARY<(
        SELECT MAX(E5.SALARY)
        FROM EMPLOYEES E5 
        WHERE E5.DEPARTMENT_ID=E.DEPARTMENT_ID
    )
)
ORDER BY E.SALARY DESC,
         D.DEPARTMENT_NAME ASC,
         E.EMPLOYEE_ID ASC;

--4
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY 
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
JOIN LOCATIONS L
ON L.LOCATION_ID=D.LOCATION_ID
WHERE (
   ((
    SELECT M.SALARY
    FROM EMPLOYEES M 
    WHERE E.MANAGER_ID=M.EMPLOYEE_ID
   )>15000 AND NOT
   (
    L.CITY='SEATLE'
   ))
   OR(
    (
        L.CITY= 'SEATLE'
    )AND NOT(
        SELECT M.SALARY
    FROM EMPLOYEES M 
    WHERE E.MANAGER_ID=M.EMPLOYEE_ID
   )>15000 
    )
   )

ORDER BY E.SALARY DESC, E.EMPLOYEE_ID ASC;


--5
SELECT E.FIRST_NAME, E.LAST_NAME,
D.DEPARTMENT_NAME, E.SALARY,
(CASE 
    when E.SALARY>10000 THEN 'HIGH'
    WHEN E.SALARY BETWEEN 5000 AND 10000 THEN 'MID'
    WHEN E.SALARY<5000 THEN 'LOW'
    END) SALARY_CATAGORY
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE E.SALARY>(
        SELECT AVG(E2.SALARY)
        FROM EMPLOYEES E2 
        WHERE E.DEPARTMENT_ID=E2.DEPARTMENT_ID
)
AND EXISTS(
    SELECT 1
    FROM EMPLOYEES E4 
    WHERE E4.SALARY<(
    SELECT AVG(E5.SALARY)
    FROM EMPLOYEES E5
    )
    AND E3.DEPARTMENT_ID = E.DEPARTMENT_ID
);
