--1
SELECT D.DEPARTMENT_NAME, COUNT(*) AS EMPCNT, ROUND(AVG(SALARY),2) AS AVGSAL
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
GROUP BY D.DEPARTMENT_ID , D.DEPARTMENT_NAME
HAVING COUNT(*)>3
ORDER BY AVGSAL DESC;

--2
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, D.DEPARTMENT_NAME 
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
JOIN LOCATIONS L 
ON D.LOCATION_ID=L.LOCATION_ID 
WHERE (L.CITY<>'Munich')
and(
     E.SALARY>(
    SELECT AVG(SALARY)
    FROM EMPLOYEES 
)
OR 
    (
       SELECT COUNT(DISTINCT EE.DEPARTMENT_ID)
       FROM EMPLOYEES EE
       WHERE EE.EMPLOYEE_ID=E.EMPLOYEE_ID
    )>1
);

--3
SELECT E.LAST_NAME, J.JOB_TITLE, E.SALARY
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID 
WHERE (
   SELECT COUNT(*)
   FROM EMPLOYEES EE
   WHERE EE.JOB_ID=E.JOB_ID 
   AND EE.SALARY<E.SALARY
)>=2
AND NOT EXISTS(
    SELECT 1 
    FROM JOB_HISTORY JH 
    WHERE JH.EMPLOYEE_ID=E.EMPLOYEE_ID 
);

--4
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME,E.SALARY,
(CASE 
WHEN E.HIRE_DATE< DATE '2005-01-01' THEN 'VETERAN'
WHEN EXTRACT(YEAR FROM E.HIRE_DATE) BETWEEN 2005 AND 2007 THEN 'MID'
WHEN EXTRACT(YEAR FROM E.HIRE_DATE)>=2008 THEN 'RECENT'
END ) AS TENURE_CATAGORY
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
WHERE E.SALARY>(
    SELECT AVG(EE.SALARY)
    FROM EMPLOYEES EE
)

UNION 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME,E.SALARY,
(CASE 
WHEN E.HIRE_DATE< DATE '2005-01-01' THEN 'VETERAN'
WHEN EXTRACT(YEAR FROM E.HIRE_DATE) BETWEEN 2005 AND 2007 THEN 'MID'
WHEN EXTRACT(YEAR FROM E.HIRE_DATE)>=2008 THEN 'RECENT'
END ) AS TENURE_CATAGORY
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
WHERE EXISTS(
    SELECT 1 
    FROM JOB_HISTORY JH 
    WHERE E.EMPLOYEE_ID=JH.EMPLOYEE_ID
)
ORDER BY SALARY DESC;
