--KHAJANA A SEC ONLINE ADVANCED SQL

--1
SELECT E.EMPLOYEE_ID, 
E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
D.DEPARTMENT_NAME, E.SALARY
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE E.SALARY>(
    SELECT AVG(SALARY)
    FROM EMPLOYEES
)
ORDER BY E.SALARY DESC;

--2
SELECT E.EMPLOYEE_ID, 
E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
E.SALARY,
D.DEPARTMENT_NAME, J.JOB_TITLE
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
JOIN JOBS J 
ON J.JOB_ID=E.JOB_ID 
WHERE (
    SELECT COUNT(*)
    FROM EMPLOYEES E1
    WHERE E.DEPARTMENT_ID=E1.DEPARTMENT_ID
)>=2
AND E.SALARY=(
    SELECT MAX(E3.SALARY)
    FROM EMPLOYEES E3 
    WHERE E.DEPARTMENT_ID=E3.DEPARTMENT_ID
    AND E3.SALARY<(
        SELECT MAX(E4.SALARY)
        FROM EMPLOYEES E4
       WHERE E4.DEPARTMENT_ID = E.DEPARTMENT_ID
    )

)
ORDER BY D.DEPARTMENT_NAME ASC,
         E.SALARY DESC;


--3
SELECT E.LAST_NAME, (
    SELECT DD.DEPARTMENT_NAME
    FROM DEPARTMENTS DD
    WHERE E.DEPARTMENT_ID=DD.DEPARTMENT_ID
) DEPT_NAME
FROM EMPLOYEES E 
WHERE E.SALARY>(
    SELECT AVG(E2.SALARY)
    FROM EMPLOYEES E2 
    WHERE E.DEPARTMENT_ID=E2.DEPARTMENT_ID
);

--4
SELECT E.EMPLOYEE_ID,
E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
D.DEPARTMENT_NAME,
E.SALARY,
(case
WHEN E.SALARY>10000 THEN 'TOP TIER'
ELSE 'STANDARD TIER'
END) "SALARY_TIER"
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME ASC,
E.SALARY DESC;
