CREATE TABLE DEPT_PAYROLL_SUMMARY (
COUNTRY_ID VARCHAR2(2),
DEPARTMENT_ID NUMBER,
DEPARTMENT_NAME VARCHAR2(30),
CITY VARCHAR2(30),
MONTHLY_PAYROLL NUMBER,
PAYROLL_BAND VARCHAR2(10),
GENERATED_BY VARCHAR2(30),
GENERATED_ON DATE
);


--FUNCTION
CREATE OR REPLACE FUNCTION GET_DEPT_PAYROLL(
    P_DEPT_ID IN NUMBER
)RETURN NUMBER IS 
--VAR
V_TOTAL_COST NUMBER;
V_EMP_CNT NUMBER;
BEGIN 
    BEGIN 
        SELECT COUNT(*)
        INTO V_EMP_CNT 
        FROM EMPLOYEES 
        WHERE DEPARTMENT_ID=P_DEPT_ID;
        EXCEPTION 
        WHEN NO_DATA_FOUND THEN 
        RETURN -1;
    END;
    IF V_EMP_CNT=0 THEN
    RETURN 0;
    END IF;

    V_TOTAL_COST:=0;

    FOR EMP_REC IN (
        SELECT E.EMPLOYEE_ID, E.SALARY 
        FROM EMPLOYEES E
        WHERE E.DEPARTMENT_ID=P_DEPT_ID
    )LOOP 
        V_TOTAL_COST:=V_TOTAL_COST+EMP_REC.SALARY*(EMP_REC.COMMISSION_PCT+1);
      END LOOP;
      RETURN V_TOTAL_COST;  
END GET_DEPT_PAYROLL;
/


--PROCEDURE 
CREATE OR REPLACE PROCEDURE BUILD_COUNTRY_PAYROLL (
P_COUNTRY_ID IN VARCHAR2,
P_STAFFED_DEPTS OUT NUMBER,
P_TOTAL_PAYROLL OUT NUMBER,
P_TOP_DEPT_ID OUT NUMBER
) IS 
--VARS
V_PAYROLL NUMBER;
BAND VARCHAR2;
PREV_PAYROLL NUMBER;
BEGIN 
    DELETE DEPT_PAYROLL_SUMMARY
    WHERE COUNTRY_ID=P_COUNTRY_ID;

    P_STAFFED_DEPTS:=0;
    P_TOTAL_PAYROLL:=0;
    P_TOP_DEPT_ID:=0;
    PREV_PAYROLL:=0;

    FOR DEPT_INFO IN (
        SELECT C.COUNTRY_ID,
        D.DEPARTMENT_ID,
        D.DEPARTMENT_NAME,
        L.CITY
        FROM DEPARTMENTS D 
        JOIN LOCATIONS L 
        ON D.LOCATION_ID=L.LOCATION_ID 
        JOIN COUNTRIES C 
        ON L.COUNTRY_ID=C.COUNTRY_ID 
        WHERE C.COUNTRY_ID=P_COUNTRY_ID
    )loop
    V_PAYROLL:=GET_DEPT_PAYROLL(DEPT_INFO.DEPARTMENT_ID);
    P_TOTAL_PAYROLL:=P_TOTAL_PAYROLL+V_PAYROLL;
    IF(V_PAYROLL>PREV_PAYROLL)then
    P_TOP_DEPT_ID:=DEPT_INFO.DEPARTMENT_ID;
    PREV_PAYROLL:=V_PAYROLL;
    ELSIF V_PAYROLL=PREV_PAYROLL
    --SMALLER DEPT ID
    END IF;

    IF V_PAYROLL=0 THEN
    BAND:='EMPTY';
    P_STAFFED_DEPTS:=P_STAFFED_DEPTS+1;
    ELSIF V_PAYROLL<=25000 THEN 
    BAND:='SMALL';
    ELSIF V_PAYROLL<=100000 THEN 
    BAND:='MEDIUM';
    ELSE 
    BAND:='LARGE';
    END IF;

    INSERT INTO DEPT_PAYROLL_SUMMARY(
        COUNTRY_ID,
        DEPARTMENT_ID,
        DEPARTMENT_NAME,
        CITY,
        MONTHLY_PAYROLL,
        PAYROLL_BAND, 
        GENERATED_BY,
        GENERATED_ON 
    )VALUES(
       P_COUNTRY_ID,
       DEPT_INFO.DEPARTMENT_ID,
       DEPT_INFO.DEPARTMENT_NAME,
       DEPT_INFO.CITY,
       V_PAYROLL,
       BAND,
       USER,
       SYSDATE 
    );
    END LOOP;
END;
/

SET SERVEROUTPUT ON;
DECLARE 
P_STAFFED_DEPTS NUMBER,
P_TOTAL_PAYROLL NUMBER,
P_TOP_DEPT_ID NUMBER
BEGIN 
    BUILD_COUNTRY_PAYROLL('US', P_STAFFED_DEPTS,P_TOTAL_PAYROLL,
    P_TOP_DEPT_ID);
 DBMS_OUTPUT.PUT_LINE( P_STAFFED_DEPTS || P_TOTAL_PAYROLL||  P_TOP_DEPT_ID);
  BUILD_COUNTRY_PAYROLL('IT', P_STAFFED_DEPTS,P_TOTAL_PAYROLL,
    P_TOP_DEPT_ID);
 DBMS_OUTPUT.PUT_LINE( P_STAFFED_DEPTS || P_TOTAL_PAYROLL||  P_TOP_DEPT_ID);
END;
/


